version: '3.7'


services:
  maks_vue:
    container_name: vue-engee
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '.:/app_engee'
    - '/app_engee/node_modules'
    ports:
    - '8080:80'